Module2 task1
htmlacademy-ecmascript/496895-big-trip-16 pull request #4
Opened 2021-12-02 11:49 UTC by TroshinSerg

2021-12-02 17:16 UTC, copperkraft requested changes

2021-12-02 17:16 UTC, copperkraft commented on src/main.js
> +  let totalPrice = 0;
Я бы предпочел чтобы ты не использовал `let` переменные, т.к. это может приводить к ошибкам и снижает читаемость кода. 

Если умеешь обращаться с `reduce`, то можно группировать несколько значений в объект, а не в простую числовую переменную, например.

2021-12-02 17:16 UTC, copperkraft commented on src/main.js
> +    if (new Date(it.dateFrom).getTime() < startDate) {
```js
startDate = Math.min(startDate, new Date(it.dateFrom).getTime())
```
Но я бы, конечно, предпочел чтобы переменная `startDate` была неизменяемой. 
Можно завести новую переменную или же сразу вернуть значение в `return`.

2021-12-02 17:16 UTC, copperkraft commented on src/main.js
> +  if (index === 0) {
Некоторые if-else конструкции можно упростить с помощью тернарных операторов
```js
renderTemplate(
  tripEventsListElement,
  createPointTemplate(point),
  index ? RenderPosition.BEFOREEND : RenderPosition.AFTERBEGIN
);
```

2021-12-02 17:16 UTC, copperkraft commented on src/mock/offer.js
> +  const titles = offerTitles.find((it) => it.type === type).titles;
А вот если бы у тебя был не массив, а объект, где ключи это названия типов, а значения -- заголовки, то было бы `const titles = offerTitleMap[type];`

2021-12-02 17:16 UTC, copperkraft commented on src/mock/point.js
> +let currentDate = dayjs().toDate();
Возможно мало смысла приводить к дате, если ты не используешь это никак кроме как снова конвертируешь в dayjs

2021-12-02 17:16 UTC, copperkraft commented on src/mock/point.js
> +    id: id,
Сокращенная форма записи
```suggestion
    id,
```

2021-12-02 17:16 UTC, copperkraft commented on src/utils.js
> +const getRandomInteger = (a = 0, b = 1) => {
Ты в итоге так и не воспользовался значениями по умолчанию.

2021-12-02 17:16 UTC, copperkraft commented on src/view/edit-point-view.js
> +  TYPES.forEach((eventType) => {
`.map(......).join('')` лучше, чем просто forEach

2021-12-03 13:36 UTC, TroshinSerg commented on src/main.js
> +const DestinationIdMap = (() => {
Не очень понял твой пример и как его применить. Использовал функцию getRandomInteger().

2021-12-03 13:38 UTC, TroshinSerg commented on src/main.js
> +const createTripInfoData = (arr) => {
Не придумал ничего лучше, чем заменить название параметра arr на pointsArray/

2021-12-03 13:43 UTC, TroshinSerg commented on src/main.js
> +    if (new Date(it.dateFrom).getTime() < startDate) {
Как можно сразу вернуть значение? Этот момент не понял.

2021-12-03 13:48 UTC, TroshinSerg commented on src/main.js
> +  if (index === 0) {
Да, согласен, но у меня в зависимости от значения index отрисовываются разные шаблоны в разные позиции. Понадобится два тернарника - для позиции и для функции шаблона.

2021-12-03 13:48 UTC, TroshinSerg commented on src/utils.js
> +const getRandomInteger = (a = 0, b = 1) => {
Исправился.

2021-12-03 13:51 UTC, TroshinSerg commented on src/main.js
> +  let totalPrice = 0;
А как обойтись без let если переменную надо перезаписать? Про reduce не понял.

2021-12-03 14:28 UTC, copperkraft commented on src/main.js
> +const DestinationIdMap = (() => {
Мой пример: 
![image](https://user-images.githubusercontent.com/19696618/144619029-4d2b7191-624b-4429-a9ef-69c75b4fdbde.png)

2021-12-03 14:29 UTC, copperkraft commented on src/main.js
> +const createTripInfoData = (arr) => {
points~~Array~~
items~~List~~

2021-12-03 14:31 UTC, copperkraft commented on src/main.js
> +    if (new Date(it.dateFrom).getTime() < startDate) {
Вместо 
```js
const foo = 1 + 2 + 3;
return { foo };
```
Пишем
```js
return { 
  foo: 1 + 2 + 3
}
```

2021-12-04 10:13 UTC, TroshinSerg commented on src/main.js
> +const DestinationIdMap = (() => {
Исправил.

2021-12-04 10:21 UTC, TroshinSerg commented on src/main.js
> +  if (index === 0) {
Значит оставить как есть или заменить тернарниками?

2021-12-04 14:39 UTC, copperkraft commented on src/mock/destination.js
> +  for (let i = 1; i <= picturesCount; i++) {
Используй .map()

2021-12-04 14:40 UTC, copperkraft commented on src/main.js
> +  if (index === 0) {
На свой вкус, я бы использовал тернарники.

2021-12-04 14:40 UTC, copperkraft commented on src/mock/point.js
> +  const TimeGap = {
Константы лучше выносить за пределы функций в начало файла.

2021-12-04 14:41 UTC, merged